In [109]:
import behavior_two_towers as b
import matplotlib.pyplot as plt
import numpy as np
import scipy as sp


%load_ext autoreload
%autoreload 2

%matplotlib inline

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [12]:

dataDict = {}

# DG imaging
dataDict['4054010.4']={}
dataDict['4054010.4']['behavior']={}
dataDict['4054010.4']['noTimeout']= ['1','2',['3','3_imaging']]
#dataDict['4054010.4']['scans'] = {'noTimeout':[['TT_train3/TT_train3_000_003',]]}



dataDict['4054010.5'] = {}
dataDict['4054010.5']['behavior'] = {}
dataDict['4054010.5']['noTimeout']={}
dataDict['4054010.5']['noTimeout']['files'] = ['1', '2', '3_imaging','4']
dataDict['4054010.5']['preTimeout'] = ['preTO_4']
dataDict['4054010.5']['Timeout'] = [['1', '1_imaging'],['2','2_imaging'],['3','3_1'],['4','4_imaging'] ]


# CA1 imaging
dataDict['4054011.1']={}
dataDict['4054011.1']['behavior']={}
dataDict['4054011.1']['noTimeout']=['1', ['2','2_1'],'3',['4','4_imaging']]
dataDict['4054011.1']['preTimeout'] = ['preTO_2']
dataDict['4054011.1']['Timeout'] = ['1',['2','2_imaging','2_postimaging']]


dataDict['4139190.1']={}
dataDict['4139190.1']['behavior']={}
dataDict['4139190.1']['noTimeout']=[['1_imaging','1_postimaging1','1_imaging2',],['2','2_imaging']]
dataDict['4139190.1']['preTimeout']=['preTO_2','preTO_4','preTO_5_1']
dataDict['4139190.1']['Timeout']=[['1','1_imaging','1_postimaging','1_postimaging2'],'2',['4','4_1'],['5_1','5_1_imaging']]


dataDict['4139190.3']={}
dataDict['4139190.3']['behavior']={}
dataDict['4139190.3']['noTimeout']=[['1_imaging2','1_postimaging2','1_imaging3','1_postimaging3'],['2','2_1'],['3','3_imaging']]
dataDict['4139190.3']['preTimeout']=['preTO_1','preTO_2']                                              
dataDict['4139190.3']['Timeout']=['1',['2','2_imaging']]


# Behavior only
dataDict['4054011.2']={}
dataDict['4054011.2']['behavior']={}
dataDict['4054011.2']['noTimeout'] = ['1','2','3']
dataDict['4054011.2']['preTimeout']=['preTO_4']
dataDict['4054011.2']['Timeout'] = ['1','2','3','4']


dataDict['4054016.1']={}
dataDict['4054016.1']['behavior']={}
dataDict['4054016.1']['noTimeout']=['1_revised','1_1','2','preTO_2']
dataDict['4054016.1']['preTimeout']=['preTO_4']
dataDict['4054016.1']['Timeout']=['1',['2','2_1'],['3','3_1'],'4']








# rzone0 = 250-300

# rzone1 = 350-400

In [106]:
print(187./215)

0.8697674418604651


In [103]:
# make 

c = b.process_data('4054011.2','1PortTower_Timeout_4_')

In [104]:
gridData, (rewardedTrials, errorTrials, omissionTrials, morphList) = c._interpolate_data()

In [105]:
trial_matrices, bin_edges, bin_centers = c.make_trial_matrices(gridData)

200
200
200


In [107]:
print(morphList)

[1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.5, 1.0, 1.0, 1.0, 0.75, 0.5, 1.0, 1.0, 0.75, 0.75, 0.5, 1.0, 1.0, 0.25, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.25, 0.75, 1.0, 1.0, 0.5, 0.25, 0.25, 0.5, 0.5, 0.0, 0.25, 1.0, 1.0, 1.0, 0.0, 0.75, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.75, 1.0, 1.0, 0.75, 1.0, 1.0, 0.0, 0.5, 1.0, 1.0, 0.5, 0.75, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.5, 0.5, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.25, 0.25, 0.25, 0.25, 1.0, 1.0, 0.5, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.25, 1.0, 1.0, 1.0, 0.75, 1.0, 1.0, 1.0, 

In [108]:
print(len(rewardedTrials)/float(len(morphList)))

0.845


In [120]:
zeroInds = np.where(np.array(morphList)==0)[0]
print(zeroInds)

oneInds = np.where(np.array(morphList)==1)[0]
print(oneInds)

quartInds = np.where(np.array(morphList)==.25)[0]
print(quartInds)

fiftyInds = np.where(np.array(morphList)==.5)[0]
print(fiftyInds)

threeQuartInds = np.where(np.array(morphList)==.75)[0]
print(threeQuartInds)

for m in [0, 1]:
    inds = [i for i in range(len(morphList)) if morphList[i]==m]
    
    print(len(inds))

[  2   6   7   8   9  15  21  22  37  38  41  45  54  55  56  57  65  66
  67  68  72  81  91  94 100 119 120 121 131 136 151 164 187 197]
[  0   1   3   4   5  10  11  12  13  14  16  17  18  19  20  23  24  25
  26  27  28  29  30  31  32  33  34  35  36  39  40  42  43  44  46  47
  48  49  50  51  52  53  58  59  60  61  62  63  64  69  70  71  73  74
  75  76  77  78  79  80  82  83  84  85  86  87  88  89  90  92  93  95
  96  97  98  99 102 103 104 107 108 112 113 115 116 117 118 124 125 133
 134 135 138 139 140 141 142 143 144 146 147 149 150 153 154 157 158 159
 160 161 162 163 167 168 169 170 171 172 177 178 180 181 182 183 184 185
 186 189 190 191 193 194 195 198 199]
[114 122 127 128 132 173 174 175 176 188]
[101 106 111 126 129 130 152 155 165 166 179]
[105 109 110 123 137 145 148 156 192 196]
34
135


In [121]:
# line plots
# speed vs position for correct trials

# speed vs position for incorrect trials

# speed vs position for morphs

In [ ]:
# rasters
# licks vs position for correct trials

# licks vs position for incorrect trials

# licks vs position for morphs

In [ ]:
# licks in each reward zone vs trial number
# extreme morphs
# normalize number of trials

# intermediate morphs

In [ ]:
# cumulative errors vs trial number

In [ ]:
# % correct per morph vs session

In [ ]:
# % lick at first tower vs morph