In [1]:
import plot_placecells

G:\My Drive\Figures\TwoTower\PlaceCells\4139190.1\\4139190.1_15_06_2018_1_
G:\My Drive\2P_Data\TwoTower\4139190.1\15_06_2018\TwoTower_noTimeout\TwoTower_noTimeout_1_000.mat


C:\Users\mplitt\MightyMorphingPhotonRangers\preprocessing.py:199: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  frame['ca inds'] = caInds
C:\Users\mplitt\Anaconda3\lib\site-packages\pandas\core\frame.py:3790: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  downcast=downcast, **kwargs)


G:\My Drive\2P_Data\TwoTower\4139190.1\15_06_2018\TwoTower_noTimeout\TwoTower_noTimeout_1_000.mat
#subsystem#not made into numpy array
Anot made into numpy array
frame diff 0
[0.00096188 0.0069345  0.00063029 ... 0.00237764 0.00103546 0.00177979]
[0.00624037 0.00316267 0.00192509 ... 0.00051485 0.00074056 0.00116142]
morph 0 place cells = 167 out of 1319 , 0.126611 
morph 1 place cells = 185 out of 1319, 0.140258
common place cells = 36
G:\My Drive\Figures\TwoTower\PlaceCells\4139190.1\\4139190.1_15_06_2018_3_
G:\My Drive\2P_Data\TwoTower\4139190.1\15_06_2018\TwoTower_noTimeout\TwoTower_noTimeout_3_000.mat
G:\My Drive\2P_Data\TwoTower\4139190.1\15_06_2018\TwoTower_noTimeout\TwoTower_noTimeout_3_000.mat
#subsystem#not made into numpy array
Anot made into numpy array
frame diff 0
[5.85554450e-03 9.07354507e-05 3.58952985e-03 ... 1.01420685e-03
 1.29868743e-03 5.77383437e-03]
[0.00436012 0.00022582 0.00021204 ... 0.00048423 0.00336756 0.00303642]
morph 0 place cells = 133 out of 1237 , 0.

C:\Users\mplitt\Anaconda3\lib\site-packages\scipy\stats\stats.py:3010: RuntimeWarning: invalid value encountered in double_scalars
  r = r_num / r_den
C:\Users\mplitt\Anaconda3\lib\site-packages\scipy\stats\stats.py:5256: RuntimeWarning: invalid value encountered in less
  x = np.where(x < 1.0, x, 1.0)  # if x > 1 then return 1.0


G:\My Drive\Figures\TwoTower\PlaceCells\4139190.1\\4139190.1_16_06_2018_2_
G:\My Drive\2P_Data\TwoTower\4139190.1\16_06_2018\TwoTower_noTimeout\TwoTower_noTimeout_2_000.mat
G:\My Drive\2P_Data\TwoTower\4139190.1\16_06_2018\TwoTower_noTimeout\TwoTower_noTimeout_2_000.mat
#subsystem#not made into numpy array
A_keepnot made into numpy array
frame diff 0
[0.00471351 0.00655565 0.00357558 ... 0.00129928 0.00032965 0.00198166]
[0.00015233 0.0003443  0.00513512 ... 0.00312096 0.0020443  0.00152086]
morph 0 place cells = 239 out of 1522 , 0.157030 
morph 1 place cells = 301 out of 1522, 0.197766
common place cells = 59
G:\My Drive\Figures\TwoTower\PlaceCells\4139190.1\\4139190.1_19_06_2018_2_
G:\My Drive\2P_Data\TwoTower\4139190.1\19_06_2018\TwoTower_Timeout\TwoTower_Timeout_2_000.mat
G:\My Drive\2P_Data\TwoTower\4139190.1\19_06_2018\TwoTower_Timeout\TwoTower_Timeout_2_000.mat
#subsystem#not made into numpy array
A_keepnot made into numpy array
frame diff 0


C:\Users\mplitt\MightyMorphingPhotonRangers\utilities.py:202: RuntimeWarning: Mean of empty slice
  zone0_speed[i]=np.nanmean(sub_frame.loc[zone0_mask,'speed'])
C:\Users\mplitt\MightyMorphingPhotonRangers\utilities.py:203: RuntimeWarning: Mean of empty slice
  zone1_speed[i] = np.nanmean(sub_frame.loc[zone1_mask,'speed'])


[0.00543999 0.00087416 0.00260987 ... 0.00143142 0.00117356 0.00323674]
[0.00580122 0.0009244  0.00074062 ... 0.00067354 0.00129416 0.00195695]
morph 0 place cells = 582 out of 1431 , 0.406709 
morph 1 place cells = 745 out of 1431, 0.520615
common place cells = 347
G:\My Drive\Figures\TwoTower\PlaceCells\4139190.1\\4139190.1_21_06_2018_3_
G:\My Drive\2P_Data\TwoTower\4139190.1\21_06_2018\TwoTower_Timeout\TwoTower_Timeout_3_000.mat
G:\My Drive\2P_Data\TwoTower\4139190.1\21_06_2018\TwoTower_Timeout\TwoTower_Timeout_3_000.mat
#subsystem#not made into numpy array
A_keepnot made into numpy array
frame diff 0
[0.0042054  0.00093153 0.00165527 ... 0.00306595 0.00396907 0.00077431]
[0.00205475 0.00119432 0.00112823 ... 0.00211286 0.00208463 0.00133726]
morph 0 place cells = 589 out of 1665 , 0.353754 
morph 1 place cells = 516 out of 1665, 0.309910
common place cells = 202
G:\My Drive\Figures\TwoTower\PlaceCells\4139190.1\\4139190.1_24_06_2018_2_
G:\My Drive\2P_Data\TwoTower\4139190.1\24_06_2

C:\Users\mplitt\MightyMorphingPhotonRangers\PlaceCellAnalysis.py:287: RuntimeWarning: invalid value encountered in true_divide
  fr_n[:,j] = gaussian_filter1d(fr[:,j]/fr[:,j].max(),2)


morph 0 place cells = 399 out of 1637 , 0.243739 
morph 1 place cells = 386 out of 1637, 0.235797
common place cells = 111
G:\My Drive\Figures\TwoTower\PlaceCells\4139190.1\\4139190.1_25_06_2018_2_
G:\My Drive\2P_Data\TwoTower\4139190.1\25_06_2018\TwoTower_Timeout\TwoTower_Timeout_2_000.mat
G:\My Drive\2P_Data\TwoTower\4139190.1\25_06_2018\TwoTower_Timeout\TwoTower_Timeout_2_000.mat
#subsystem#not made into numpy array
A_keepnot made into numpy array
frame diff 0
[2.43725582e-03 4.50698133e-05 2.90957745e-03 ... 6.51810881e-04
 1.03916074e-04 2.99222349e-03]
[0.00180879 0.00474095 0.00418937 ... 0.00052736 0.00299182 0.00032413]
morph 0 place cells = 396 out of 1687 , 0.234736 
morph 1 place cells = 301 out of 1687, 0.178423
common place cells = 79
G:\My Drive\Figures\TwoTower\PlaceCells\4139190.1\\4139190.1_27_06_2018_2_
G:\My Drive\2P_Data\TwoTower\4139190.1\27_06_2018\TwoTower_Timeout\TwoTower_Timeout_2_000.mat
G:\My Drive\2P_Data\TwoTower\4139190.1\27_06_2018\TwoTower_Timeout\TwoTo

C:\Users\mplitt\MightyMorphingPhotonRangers\PlaceCellAnalysis.py:284: RuntimeWarning: Mean of empty slice
  fr = np.squeeze(np.nanmean(C_morph_dict[m],axis=0))
C:\Users\mplitt\Anaconda3\lib\site-packages\numpy\core\_methods.py:28: RuntimeWarning: invalid value encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims, initial)


morph 0 place cells = 369 out of 1478 , 0.249662 
morph 1 place cells = 275 out of 1478, 0.186062
common place cells = 66


C:\Users\mplitt\Anaconda3\lib\site-packages\matplotlib\image.py:405: UserWarning: Warning: converting a masked element to nan.
  dv = (np.float64(self.norm.vmax) -
C:\Users\mplitt\Anaconda3\lib\site-packages\matplotlib\image.py:406: UserWarning: Warning: converting a masked element to nan.
  np.float64(self.norm.vmin))
C:\Users\mplitt\Anaconda3\lib\site-packages\matplotlib\image.py:413: UserWarning: Warning: converting a masked element to nan.
  a_min = np.float64(newmin)
C:\Users\mplitt\Anaconda3\lib\site-packages\matplotlib\image.py:418: UserWarning: Warning: converting a masked element to nan.
  a_max = np.float64(newmax)
C:\Users\mplitt\Anaconda3\lib\site-packages\matplotlib\colors.py:916: UserWarning: Warning: converting a masked element to nan.
  dtype = np.min_scalar_type(value)
C:\Users\mplitt\Anaconda3\lib\site-packages\numpy\ma\core.py:715: UserWarning: Warning: converting a masked element to nan.
  data = np.array(a, copy=False, subok=subok)


G:\My Drive\Figures\TwoTower\PlaceCells\4139190.1\\4139190.1_11_07_2018_17_
G:\My Drive\2P_Data\TwoTower\4139190.1\11_07_2018\TwoTower_Timeout\TwoTower_Timeout_017_023.mat
G:\My Drive\2P_Data\TwoTower\4139190.1\11_07_2018\TwoTower_Timeout\TwoTower_Timeout_017_023.mat
#subsystem#not made into numpy array
Anot made into numpy array
frame diff 0
[2.16329737e-03 7.92984214e-04 3.02098099e-04 2.03177344e-03
 8.88195274e-04 3.35982474e-03 3.29136655e-03 2.31447664e-04
 1.84937429e-03 3.45527626e-04 7.18704876e-04 1.50731335e-04
 1.38797781e-03 2.88156255e-03 9.13843813e-04 1.04863700e-03
 3.52648054e-03 2.19655456e-03 8.46079676e-04 1.53063353e-03
 1.23524208e-03 2.19952482e-03 1.08677376e-03 1.85074402e-03
 3.17790935e-03 6.30402463e-04 1.11607663e-03 2.27217561e-03
 6.60583024e-04 2.11594141e-03 8.42569427e-04 5.22814281e-04
 3.52417795e-04 1.33607304e-03 6.42391963e-04 1.37749084e-03
 1.62448941e-03 3.76063135e-04 3.09736226e-04 3.67121167e-03
 1.28687627e-03 5.49401385e-03 5.69426579e-03

C:\Users\mplitt\Anaconda3\lib\site-packages\matplotlib\pyplot.py:522: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  max_open_warning, RuntimeWarning)


morph 0 place cells = 351 out of 864 , 0.406250 
morph 1 place cells = 288 out of 864, 0.333333
common place cells = 129
G:\My Drive\Figures\TwoTower\PlaceCells\4139190.3\\4139190.3_15_06_2018_1_
G:\My Drive\2P_Data\TwoTower\4139190.3\15_06_2018\TwoTower_noTimeout\TwoTower_noTimeout_1_000.mat
G:\My Drive\2P_Data\TwoTower\4139190.3\15_06_2018\TwoTower_noTimeout\TwoTower_noTimeout_1_000.mat
#subsystem#not made into numpy array
A_keepnot made into numpy array
frame diff 0
[3.23121314e-03 5.09970276e-04 7.99472335e-04 2.84598468e-03
 4.39201449e-03 9.93008324e-04 1.39673318e-03 3.39248337e-03
 8.28729958e-04 1.64971939e-03 2.39306982e-03 1.12919969e-03
 1.93386802e-03 1.75296364e-03 5.91740821e-04 1.49154094e-03
 1.20834689e-03 4.91241606e-04 1.59624982e-03 7.79167013e-04
 2.92640367e-03 1.34158865e-03 4.10472894e-03 1.48652476e-03
 1.36368634e-03 3.46157087e-03 1.84121766e-03 6.38169848e-04
 2.94379595e-03 4.30826868e-04 1.29195057e-03 4.76883029e-03
 1.18352170e-03 5.50028888e-03 1.20511

C:\Users\mplitt\Anaconda3\lib\site-packages\pandas\core\indexing.py:189: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)


G:\My Drive\2P_Data\TwoTower\4139212.2\15_10_2018\TwoTower_Timeout\TwoTower_Timeout_002_001.mat
#subsystem#not made into numpy array
Anot made into numpy array
frame diff 0
[0.00239322 0.00091832 0.00075754 ... 0.00042214 0.00124661 0.00216767]
[0.00280476 0.00346182 0.00079719 ... 0.00259156 0.0029308  0.00117982]
morph 0 place cells = 609 out of 1284 , 0.474299 
morph 1 place cells = 529 out of 1284, 0.411994
common place cells = 255
G:\My Drive\Figures\TwoTower\PlaceCells\4139212.2\\4139212.2_17_10_2018_1_
G:\My Drive\2P_Data\TwoTower\4139212.2\17_10_2018\TwoTower_Timeout\TwoTower_Timeout_001_001.mat
G:\My Drive\2P_Data\TwoTower\4139212.2\17_10_2018\TwoTower_Timeout\TwoTower_Timeout_001_001.mat
#subsystem#not made into numpy array
Anot made into numpy array
frame diff 0
[0.00132379 0.00131293 0.00446001 ... 0.00144562 0.00066261 0.00621104]
[0.00307622 0.00179789 0.00116739 ... 0.00358932 0.00364203 0.00369085]
morph 0 place cells = 325 out of 1195 , 0.271967 
morph 1 place cells = 

C:\Users\mplitt\MightyMorphingPhotonRangers\PlaceCellAnalysis.py:213: RuntimeWarning: Mean of empty slice
  FR[m]['even'] = np.nanmean(C_morph_dict[m][1::2,:,:],axis=0)


[4.27725254e-03 7.26032419e-03 6.02441638e-03 2.33446045e-03
 2.16489883e-03 5.96448647e-03 1.68358854e-03 7.16289308e-03
 2.79704631e-03 1.81631605e-03 3.33917206e-03 2.16479293e-03
 1.46381514e-03 1.43173002e-03 1.82232166e-03 7.94285033e-04
 2.33756960e-03 1.40152734e-03 1.59681009e-03 5.92580547e-04
 3.30161869e-04 3.24703654e-04 2.70845563e-03 1.77124616e-03
 2.84030777e-03 3.81524758e-03 4.87539916e-03 1.37323031e-03
 2.18318325e-03 4.32612670e-03 4.97020654e-03 1.87152793e-03
 3.39273594e-03 1.29683935e-03 4.62116384e-03 2.95568984e-03
 3.44296898e-03 2.67042950e-03 1.01817871e-03 1.35796676e-03
 6.12976719e-03 5.81811690e-03 7.73239451e-04 1.86797646e-03
 7.17189047e-03 7.56209433e-03 7.57171205e-04 2.29420067e-03
 3.21383231e-03 4.24776124e-03 1.65834677e-03 1.12181220e-02
 4.98690436e-04 3.28106721e-03 5.01574657e-03 8.52842167e-03
 3.60379547e-03 1.30080503e-03 1.37254559e-03 3.16929219e-03
 5.71980870e-03 3.75652764e-03 4.46889132e-03 7.55434603e-03
 4.07075052e-03 4.484569

C:\Users\mplitt\Anaconda3\lib\site-packages\matplotlib\axes\_base.py:3471: UserWarning: Attempting to set identical bottom==top results
in singular transformations; automatically expanding.
bottom=-0.5, top=-0.5
  'bottom=%s, top=%s') % (bottom, top))


morph 0 place cells = 1 out of 8 , 0.125000 
morph 1 place cells = 0 out of 8, 0.000000
common place cells = 0
G:\My Drive\Figures\TwoTower\PlaceCells\4139219.3\\4139219.3_26_10_2018_1_
G:\My Drive\2P_Data\TwoTower\4139219.3\26_10_2018\TwoTower_Timeout\TwoTower_Timeout_001_001.mat
G:\My Drive\2P_Data\TwoTower\4139219.3\26_10_2018\TwoTower_Timeout\TwoTower_Timeout_001_001.mat
#subsystem#not made into numpy array
Anot made into numpy array
frame diff 0
[3.51730851e-03 4.73305332e-03 3.02516843e-03 9.66424618e-04
 1.80917338e-03 3.51597386e-03 4.09998489e-03 8.56635066e-04
 8.94753381e-04 3.10246442e-03 7.35530776e-04 1.84714981e-03
 2.68209529e-03 2.83374843e-03 4.24526023e-03 5.27511195e-03
 1.71657241e-03 2.40958786e-03 2.62303533e-03 2.56907085e-03
 8.56296064e-04 2.05116723e-03 2.97997030e-03 2.42230291e-03
 6.39217082e-03 6.44168769e-03 1.91225344e-03 1.20818636e-03
 2.22546610e-03 3.75168982e-03 9.60487031e-04 6.78667105e-03
 3.17564266e-03 4.17550894e-03 4.30667809e-03 2.52610476e